//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber
    {
        public string openid { get; set; }
        public bool subscribe { get; set; }
        public string nickname { get; set; }
        public string sex { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string strlanguage { get; set; }
        public string headimgurl { get; set; }
        public string subscribe_time { get; set; }
        public string unionid { get; set; }
        public string groupid { get; set; }
        public string tagid_list { get; set; }
        public string subscribe_scene { get; set; }
        public string qr_scene { get; set; }
        public string qr_scene_str { get; set; }
        public string remark { get; set; }
    }
}
