//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenu
    {
        public string ID { get; set; }
        public string ParentID { get; set; }
        public string sName { get; set; }
        public string sTag { get; set; }
        public string sUrl { get; set; }
        public string sIconUrl { get; set; }
        public string remark { get; set; }
        public int sort { get; set; }
        public int numstate { get; set; }
    }
}
