//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOperateLog
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> dtLoginIn { get; set; }
        public Nullable<System.DateTime> dtLoginOut { get; set; }
        public string sIpAddress { get; set; }
        public string sTimeLength { get; set; }
        public string remark { get; set; }
        public int numstate { get; set; }
    }
}
