//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wxmsmResponse
    {
        public string ID { get; set; }
        public string eventType { get; set; }
        public string resMessageType { get; set; }
        public string eventKey { get; set; }
        public string msgContent { get; set; }
        public string Title { get; set; }
        public string msgDescription { get; set; }
        public string PicUrl { get; set; }
        public string Url { get; set; }
        public string MediaId { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<bool> numstate { get; set; }
    }
}
